name: "\U0001F41B Bug report"
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues found within starterpack core.
        If you require more general support please message the moderators. https://www.reddit.com/message/compose/?to=/r/starterpacks

        Please fill in as much of the form below as you're able.
  - type: input
    attributes:
      label: Platform
      description: |
        UNIX: output of `uname -a`
        Windows: output of `"$([Environment]::OSVersion | ForEach-Object VersionString) $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" })"` in PowerShell console
  - type: input
    attributes:
      label: Browser version
      description: Visit https://www.whatismybrowser.com/.
  - type: input
    attributes:
      label: RES
      description: If known, please specify the RES version if used.
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug.
  - type: textarea
    attributes:
      label: How often does it reproduce? Is there a required condition?
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide screenshots.
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
